//
// Created by gaugamela on 8/31/25.
//

#ifndef DRAWUTILSCONVENIENCEFUNCTIONS_HPP
#define DRAWUTILSCONVENIENCEFUNCTIONS_HPP

#define DEFAULT_FRAMEBUF_CHAR '.'

#endif // DRAWUTILSCONVENIENCEFUNCTIONS_HPP
